### ISSUE TITLE
显示成功，但是压缩率为0

### ISSUE THREAD

**Issue by qc-z** [vbenjs/vite-plugin-imagemin#22]
vite-plugin-imagemin:"version": "0.5.1"
![image](https://user-images.githubusercontent.com/22362903/148905581-d90bc386-effd-41b9-9767-1c9182a3b80e.png)
vite:"version": "2.7.6",
![image](https://user-images.githubusercontent.com/22362903/148905654-526981cd-845f-4fe3-8b99-345b20d39ac6.png)

**Comment by anncwb** [comment]
Fixed in 0.5.2
