### ISSUE TITLE
0.5.2打包异常

### ISSUE THREAD

**Issue by bangxingni** [vbenjs/vite-plugin-imagemin#23]
windows环境下 根目录public文件夹下的图片 打包提示找不到路径 ，  0.5.1 可以

**Comment by anncwb** [comment]
可以给一个错误截图吗？

**Comment by bangxingni** [comment]
![image](https://user-images.githubusercontent.com/20875524/150928015-8b194317-d60d-4cba-85a4-8c8146109fff.png)
![image](https://user-images.githubusercontent.com/20875524/150928181-b9aeaddb-f06f-46b7-ae4c-b2238c5c9641.png)
