### ISSUE TITLE
这个插件实在是太难安装了

### ISSUE THREAD

**Issue by Adaer** [vbenjs/vite-plugin-imagemin#31]
connect ETIMEDOUT 199.232.4.133:443
无论是按照说明文档，还是用梯子，基本都是超时timeout，太难了

**Comment by Adaer** [comment]
终于找到正确的安装方法了
`npm i vite-plugin-imagemin -D --ignore-scripts`

**Comment by qs5639** [comment]
设置host代理为“185.199.109.133 raw.githubusercontent.com
