### ISSUE TITLE
Jenkins 自动部署在linux下安装依赖就报错version `ZLIB_1.2.9' not found （Vben Admin 用到本插件）

### ISSUE THREAD

**Issue by adoin** [vbenjs/vite-plugin-imagemin#38]

**Comment by AndyYang2014** [comment]
node_modules/mozjpeg/vendor/cjpeg: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found   是不是一毛一样

**Comment by adoin** [comment]
> node_modules/mozjpeg/vendor/cjpeg: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found 是不是一毛一样

对的。。。然后我忘了咋就解决了

**Comment by vintonHuang** [comment]
這個問題是怎麼解決的啊。沒有看到解決方案啊
